linux: &linux
   os: linux
   sudo: true   
   dist: xenial
   language: python
   python: "3.7"
   services:
     - docker
     
osx: &osx
   os: osx
   language: generic

branches:
  only:
    - master
    - /^stable\/.*$/

env:
   global:
     - CONAN_REMOTES: "https://api.bintray.com/conan/conan-community/conan,https://api.bintray.com/conan/bincrafters/public-conan,https://api.bintray.com/conan/vthiery/conan-packages"

matrix:
   include:
    - <<: *linux
      env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7
    - <<: *linux
      env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8
    - <<: *linux
      env: CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/gcc9
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=7.0 CONAN_DOCKER_IMAGE=conanio/clang7
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/clang8
    - <<: *osx
      osx_image: xcode10.2
      env: CONAN_APPLE_CLANG_VERSIONS=10.0
    - os: linux
      dist: xenial    
      addons:
        apt:
          packages:
            - doxygen
            - doxygen-doc
            - doxygen-latex
            - doxygen-gui
            - graphviz

      env:
      - BUILD_DOCS="YES"

install:
  - if [ "$BUILD_DOCS" != "YES" ]; then
      chmod +x .travis/install.sh;
      ./.travis/install.sh;
    fi

script:
  - if [ "$BUILD_DOCS" != "YES" ]; then
      chmod +x .travis/run.sh;
      ./.travis/run.sh;
    fi
  - if [ "$BUILD_DOCS" == "YES" ]; then
      doxygen Doxyfile;
    fi    

deploy:
  if: env(BUILD_DOCS)="YES"
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master